-- | Renders a 'CrdDef' (a parsed CRD's identity + spec\/status schemas) as
-- Haskell source text: one record type per schema object (nested objects
-- get their own, separately-named type), hand-rolled-shaped
-- 'Data.Aeson.FromJSON'\/'Data.Aeson.ToJSON' instances built the same way
-- "Kubernetes.Resource"'s @envelope*@ helpers expect, and a
-- 'Kubernetes.Resource.Resource' instance tying it all together.
--
-- Deliberately generates plain source text rather than going through
-- @template-haskell@ or an AST library: the output is meant to be read,
-- committed, and hand-edited afterwards, not regenerated on every build —
-- treat it the same way you'd treat `kubectl create -o yaml --dry-run`
-- output, a starting point, not a black box.
module Kubernetes.Codegen.Generate
  ( generateModule
  ) where

import qualified Data.Char as Char
import qualified Data.Map.Strict as Map
import Data.Text (Text)
import qualified Data.Text as T
import Kubernetes.Codegen.Schema (CrdDef (..), Schema (..))

-- | One generated declaration block (a @data@ decl plus its instances, or
-- an enum decl plus its instances) together with a note of which type name
-- it defines, so callers can dedupe when the same shape is reachable from
-- two paths (rare, but e.g. two sibling fields with an identical inline
-- object schema would otherwise generate the same type twice).
data Decl = Decl {declName :: !Text, declText :: !Text}

-- | A schema rendered at some point in the tree: the Haskell type
-- expression to use right here, plus any new top-level declarations that
-- had to be introduced to name that type.
data Rendered = Rendered {rTypeExpr :: !Text, rDecls :: ![Decl]}

generateModule :: Text -> CrdDef -> Text
generateModule moduleName crd =
  T.unlines $
    [ "{-# LANGUAGE OverloadedStrings #-}"
    , ""
    , "-- | GENERATED by crd-codegen from a CustomResourceDefinition manifest."
    , "-- Edit freely — this file is not regenerated automatically — but if"
    , "-- you do regenerate it, diff first: hand edits and generator output"
    , "-- will conflict textually, not just semantically."
    , "module " <> moduleName <> " where"
    , ""
    , "import qualified Data.Aeson as Aeson"
    , "import Data.Aeson ((.:), (.:?), (.=))"
    , "import Data.Map.Strict (Map)"
    , "import qualified Data.Maybe as Maybe"
    , "import Data.Text (Text)"
    , "import Kubernetes.Resource"
    , ""
    ]
      ++ concatMap (declLines . declText) allDecls
      ++ resourceInstance
  where
    kind = crdKind crd
    specRendered = renderSchema [kind, "Spec"] (crdSpecSchema crd)
    statusRendered = fmap (renderSchema [kind, "Status"]) (crdStatusSchema crd)

    wrapperDecl = renderWrapper crd specRendered statusRendered

    allDecls =
      dedupe (rDecls specRendered ++ maybe [] rDecls statusRendered ++ [wrapperDecl])

    declLines t = [t, ""]

    resourceInstance =
      [ "instance Resource " <> kind <> " where"
      , "  resourceGVK _ = GVK " <> hsString (crdGroup crd) <> " " <> hsString (crdVersionName crd) <> " " <> hsString kind
      , "  resourceScope _ = " <> if crdScopeNamespaced crd then "Namespaced" else "ClusterScoped"
      , "  resourcePlural _ = " <> hsString (crdPlural crd)
      , "  resourceMeta = " <> fieldName [kind] "metadata"
      , "  resourceSetMeta m x = x {" <> fieldName [kind] "metadata" <> " = m}"
      ]

-- | Later declarations win on a name clash (shouldn't happen for distinct
-- schemas, since names are derived from distinct field paths) but two
-- *identical* inline schemas reachable from different paths would
-- otherwise be emitted twice with different names — not deduped, since
-- doing so correctly needs structural equality on 'Schema', which the
-- small win doesn't justify here. What /is/ deduped is emitting the exact
-- same 'Decl' (same name) more than once.
dedupe :: [Decl] -> [Decl]
dedupe = go [] []
  where
    go _ acc [] = reverse acc
    go seen acc (d : ds)
      | declName d `elem` seen = go seen acc ds
      | otherwise = go (declName d : seen) (d : acc) ds

-- --------------------------------------------------------------------------
-- Naming
-- --------------------------------------------------------------------------

upperFirst :: Text -> Text
upperFirst t = case T.uncons t of
  Nothing -> t
  Just (c, rest) -> T.cons (Char.toUpper c) rest

lowerFirst :: Text -> Text
lowerFirst t = case T.uncons t of
  Nothing -> t
  Just (c, rest) -> T.cons (Char.toLower c) rest

-- | Turn a field path (e.g. @["MyApp","Spec","Template"]@) into a type
-- name (@"MyAppSpecTemplate"@).
typeName :: [Text] -> Text
typeName = T.concat . map upperFirst

-- | A record field name unique across the whole generated module: the
-- owning type's name (which already encodes its full path) followed by
-- the property name, e.g. type @MyAppSpec@ field @replicas@ becomes
-- @myAppSpecReplicas@.
fieldName :: [Text] -> Text -> Text
fieldName path leaf = lowerFirst (typeName path) <> upperFirst (sanitizeIdent leaf)

-- | Best-effort valid-Haskell-identifier sanitization for property\/enum
-- names that aren't already one (dashes, dots, and leading digits are the
-- realistic cases from CRDs using e.g. DNS-label-style or numeric-looking
-- values).
sanitizeIdent :: Text -> Text
sanitizeIdent t0 =
  let t1 = T.concatMap (\c -> if Char.isAlphaNum c then T.singleton c else "_") t0
   in case T.uncons t1 of
        Just (c, _) | Char.isDigit c -> "N" <> t1
        _ -> if T.null t1 then "Empty" else t1

hsString :: Text -> Text
hsString t = T.pack (show t) -- relies on Haskell's `String`/`Text` Show quoting matching valid source syntax

-- --------------------------------------------------------------------------
-- Schema -> declarations
-- --------------------------------------------------------------------------

renderSchema :: [Text] -> Schema -> Rendered
renderSchema _ SInteger = Rendered "Int" []
renderSchema _ SNumber = Rendered "Double" []
renderSchema _ SBoolean = Rendered "Bool" []
renderSchema _ SIntOrString = Rendered "IntOrString" []
renderSchema _ SAny = Rendered "Aeson.Value" []
renderSchema _ (SString Nothing) = Rendered "Text" []
renderSchema path (SString (Just values)) =
  Rendered tyName [Decl tyName (renderEnum tyName values)]
  where
    tyName = typeName path
renderSchema path (SArray item) =
  let ir = renderSchema (path ++ ["Item"]) item
   in Rendered ("[" <> rTypeExpr ir <> "]") (rDecls ir)
renderSchema path (SMap value) =
  let vr = renderSchema (path ++ ["Value"]) value
   in Rendered ("(Map Text " <> parenthesize (rTypeExpr vr) <> ")") (rDecls vr)
renderSchema path (SObject props required) =
  let tyName = typeName path
      propList = Map.toList props
      fields =
        [ (propName, renderSchema (path ++ [propName]) propSchema, propName `elem` required)
        | (propName, propSchema) <- propList
        ]
      nestedDecls = concatMap (\(_, r, _) -> rDecls r) fields
      recordFields = [(fieldName path propName, r, propName, req) | (propName, r, req) <- fields]
      decl = renderRecord tyName recordFields
   in Rendered tyName (nestedDecls ++ [Decl tyName decl])

parenthesize :: Text -> Text
parenthesize t
  | T.any (== ' ') t = "(" <> t <> ")"
  | otherwise = t

renderEnum :: Text -> [Text] -> Text
renderEnum tyName values =
  T.unlines $
    [ "data " <> tyName <> " = " <> T.intercalate " | " ctors
    , "  deriving (Show, Eq)"
    , ""
    , "instance Aeson.FromJSON " <> tyName <> " where"
    ]
      ++ [ "  parseJSON (Aeson.String " <> hsString v <> ") = pure " <> c
         | (c, v) <- zip ctors values
         ]
      ++ [ "  parseJSON v = fail (\"unknown " <> tyName <> " value: \" ++ show v)"
         , ""
         , "instance Aeson.ToJSON " <> tyName <> " where"
         ]
      ++ ["  toJSON " <> c <> " = Aeson.String " <> hsString v | (c, v) <- zip ctors values]
  where
    ctors = [tyName <> upperFirst (sanitizeIdent v) | v <- values]

-- | A record type plus its 'Data.Aeson.FromJSON'\/'Data.Aeson.ToJSON'
-- instances, built as an ordinary applicative-chain parser and an
-- explicit-field-list encoder — the same shape a human would hand-write,
-- deliberately not routed through Generic\/anyclass deriving so the JSON
-- keys (the original CRD property names) can differ from the generated
-- Haskell field names (which are prefixed for global uniqueness).
renderRecord :: Text -> [(Text, Rendered, Text, Bool)] -> Text
renderRecord tyName fields =
  T.unlines $
    [dataLine]
      ++ fieldLines
      ++ [ "  deriving (Show, Eq)"
         , ""
         , "instance Aeson.FromJSON " <> tyName <> " where"
         , "  parseJSON = Aeson.withObject " <> hsString tyName <> " $ \\o -> " <> tyName
         ]
      ++ parseLines
      ++ [ ""
         , "instance Aeson.ToJSON " <> tyName <> " where"
         , "  toJSON x = Aeson.object (Maybe.catMaybes"
         ]
      ++ toJsonLines
      ++ ["    ])"]
  where
    dataLine = "data " <> tyName <> " = " <> tyName
    fieldLines =
      [ "  " <> prefix <> hsName <> " :: " <> ty
      | (idx, (hsName, r, _, req)) <- zip [0 :: Int ..] fields
      , let prefix = if idx == 0 then "{ " else ", "
            ty = if req then rTypeExpr r else "Maybe (" <> rTypeExpr r <> ")"
      ]
        ++ (if null fields then ["  {"] else [])
        ++ ["  }"]
    parseLines =
      [ "    " <> prefix <> "o " <> (if req then ".:" else ".:?") <> " " <> hsString jsonKey
      | (idx, (_, _, jsonKey, req)) <- zip [0 :: Int ..] fields
      , let prefix = if idx == 0 then "<$> " else "<*> "
      ]
    toJsonLines =
      [ "    " <> prefix <> line
      | (idx, (hsName, _, jsonKey, req)) <- zip [0 :: Int ..] fields
      , let prefix = if idx == 0 then "[ " else ", "
            accessor = hsName <> " x"
            line =
              if req
                then "Just (" <> hsString jsonKey <> " .= " <> accessor <> ")"
                else "fmap (" <> hsString jsonKey <> " .=) (" <> accessor <> ")"
      ]

-- | The top-level wrapper type combining 'ObjectMeta' with the generated
-- spec (and, if present, status) types, using
-- 'Kubernetes.Resource.envelopeParseJSON'\/'envelopeToJSON' rather than
-- repeating the envelope shape by hand.
renderWrapper :: CrdDef -> Rendered -> Maybe Rendered -> Decl
renderWrapper crd specR statusR =
  Decl kind . T.unlines $
    [ "data " <> kind <> " = " <> kind
    , "  { " <> metaField <> " :: ObjectMeta"
    , "  , " <> specField <> " :: " <> rTypeExpr specR
    ]
      ++ maybe [] (\r -> ["  , " <> statusField <> " :: Maybe (" <> rTypeExpr r <> ")"]) statusR
      ++ [ "  }"
         , "  deriving (Show, Eq)"
         , ""
         , "instance Aeson.FromJSON " <> kind <> " where"
         , "  parseJSON v = do"
         , -- When there's no generated Status type, `status` in
           -- `envelopeParseJSON`'s result type is otherwise unconstrained
           -- (`st` is never used) — pin it to `()` explicitly rather than
           -- leaving it ambiguous.
           "    (m, s, st" <> (if hasStatus then "" else " :: Maybe ()") <> ") <- envelopeParseJSON v"
         , "    pure (" <> kind <> " m s" <> (if hasStatus then " st" else "") <> ")"
         , ""
         , "instance Aeson.ToJSON " <> kind <> " where"
         , "  toJSON x = envelopeToJSON (GVK "
             <> hsString (crdGroup crd)
             <> " "
             <> hsString (crdVersionName crd)
             <> " "
             <> hsString kind
             <> ") ("
             <> metaField
             <> " x) ("
             <> specField
             <> " x) "
             <> statusExpr
         ]
  where
    kind = crdKind crd
    hasStatus = case statusR of Just _ -> True; Nothing -> False
    metaField = fieldName [kind] "metadata"
    specField = fieldName [kind] "spec"
    statusField = fieldName [kind] "status"
    statusExpr = case statusR of
      Nothing -> "(Nothing :: Maybe ())"
      Just _ -> "(" <> statusField <> " x)"
